
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: bike_station_with_network_data
    description: Base bike station data with network information attached
    columns:
      - name: station_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: companies
    description: Clean list of all companies and countries
    columns:
      - name: unique_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

sources:
  - name: dezoomcamp
    description: Raw data from the City Bike API
    schema: dezoomcamp  # The schema where the source table exists
    tables:
      - name: networks
        description: Raw network data from the City Bike API
      - name: bike_station_data
        description: Raw bike station data from the City Bike API
